---

- hosts: vyos

  connection:  ansible.netcommon.network_cli
  gather_facts: 'no'

  vars:
      ansible_network_os: vyos.vyos.vyos
      ansible_user: vyos
      ansible_password: vyos

  roles:
    - vyos_hostname
    - vyos_interfaces
    - vyos_routing

- hosts: debian

  roles:
    - debian_hostname
