---

hostname: AS1-RTR1
domain_name: AS1.lab

loopback:
  dum0:
    alias: dummy loopback0
    address: 10.10.0.11
    mask: /32

interfaces:
  eth1:
    alias: 1R1-2R1
    address: 10.10.12.1
    mask: /30

  eth2:
    alias: 1R1-1R2
    address: 10.10.1.1
    mask: /30
    
  eth3:
    alias: 1R1-1R3
    address: 10.10.1.13
    mask: /30

bgp:
  asn: 65501
  neighbor:
    - {address: 10.10.12.2, remote_as: 65502}
    - {address: 10.10.1.2, remote_as: 65501}
    - {address: 10.10.1.14, remote_as: 65501}
  networks:
    - {network: 10.10.12.0, mask: /30}
    - {network: 10.10.1.0, mask: /30}
    - {network: 10.10.1.12, mask: /30}
    - {network: 10.10.0.11, mask: /32}
  maxpath: 2
