---

hostname: AS2-RTR1
domain_name: AS2.lab

loopback:
  dum0:
    alias: dummy loopback0
    address: 10.10.0.21
    mask: /32

interfaces:
  eth1:
    alias: 2R1-1R1
    address: 10.10.12.2
    mask: /30

  eth2:
    alias: 2R1-2R2
    address: 10.10.2.1
    mask: /30
    
  eth3:
    alias: 2R1-2R3
    address: 10.10.2.5
    mask: /30

bgp:
  asn: 65502
  neighbor:
    - {address: 10.10.12.1, remote_as: 65501}
    - {address: 10.10.2.2, remote_as: 65502}
    - {address: 10.10.2.6, remote_as: 65502}
  networks:
    - {network: 10.10.12.0, mask: /30}
    - {network: 10.10.2.0, mask: /30}
    - {network: 10.10.2.4, mask: /30}
    - {network: 10.10.0.21, mask: /32}
  maxpath: 5
