---

hostname: AS3-RTR2
domain_name: AS3.lab

loopback:
  dum0:
    alias: dummy loopback0
    address: 10.10.0.32
    mask: /32

interfaces:
  eth1:
    alias: 3R2-2R2
    address: 10.10.23.2
    mask: /30

  eth2:
    alias: 3R2-3R3
    address: 10.10.3.1
    mask: /30
    
  eth3:
    alias: 3R2-3C
    address: 10.10.3.9
    mask: /30

bgp:
  asn: 65503
  neighbor:
    - {address: 10.10.23.1, remote_as: 65502}
    - {address: 10.10.3.2, remote_as: 65503}
  networks:
    - {network: 10.10.23.0, mask: /30}
    - {network: 10.10.3.0, mask: /30}
    - {network: 10.10.3.8, mask: /30}
    - {network: 10.10.0.32, mask: /32}
  maxpath: 2
