---

hostname: AS4-RTR3
domain_name: AS4.lab

loopback:
  dum0:
    alias: dummy loopback0
    address: 10.10.0.43
    mask: /32

interfaces:
  eth1:
    alias: 4R3-4R2
    address: 10.10.4.6
    mask: /30

  eth2:
    alias: 4R3-2R2
    address: 10.10.24.2
    mask: /30

bgp:
  asn: 65504
  neighbor:
    - {address: 10.10.4.5, remote_as: 65504}
    - {address: 10.10.24.1, remote_as: 65502}
  networks:
    - {network: 10.10.4.4, mask: /30}
    - {network: 10.10.24.0, mask: /30}
    - {network: 10.10.0.43, mask: /32}
  maxpath: 2
