---

hostname: AS4-RTR2
domain_name: AS4.lab

loopback:
  dum0:
    alias: dummy loopback0
    address: 10.10.0.42
    mask: /32

interfaces:
  eth1:
    alias: 4R2-4R1
    address: 10.10.4.2
    mask: /30

  eth2:
    alias: 4R2-4R3
    address: 10.10.4.5
    mask: /30
    
  eth3:
    alias: 4R2-4C
    address: 10.10.4.9
    mask: /30

bgp:
  asn: 65504
  neighbor:
    - {address: 10.10.4.1, remote_as: 65504}
    - {address: 10.10.4.6, remote_as: 65504}
  networks:
    - {network: 10.10.4.0, mask: /30}
    - {network: 10.10.4.4, mask: /30}
    - {network: 10.10.4.8, mask: /30}
    - {network: 10.10.0.42, mask: /32}
  maxpath: 5
